
name: PMD
on:
  push:

jobs:
  pmd:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: PMD Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: pmd/pmd-github-action@v1
        id: pmd
        with:
          version: '6.40.0'
          rulesets: 'rulesets/java/quickstart.xml'
          sourcePath: 'src/main/java'
          analyzeModifiedFilesOnly: false
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pmd-report.sarif


